import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../styles/globals.scss";
import Provider from "@/app/theme";
import dayjs from "dayjs";
import "dayjs/locale/ru";
import { ReactNode } from "react";
import { ProgressBar } from "@/components/progress-bar/progress-bar";

const geist = Geist({
  subsets: ["latin"],
});

dayjs.locale("ru");

export const metadata: Metadata = {
  title: "ERM Фасады Сысолы - фабрика мебельных фасадов",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geist.className} antialiased`}>
        <Provider>
          <ProgressBar>{children}</ProgressBar>
        </Provider>
      </body>
    </html>
  );
}
export const runtime = "nodejs";
